on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
    
jobs:
  validate:
    name: Validate XML files with XMLStarlet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate 73 tokens
        uses: Mudlet/xmlstarlet-action@v1.1
        with:
          args: 'val -b 73.xml'
          
      - name: Validate 8X tokens
        uses: Mudlet/xmlstarlet-action@v1.1
        with:
          args: 'val -b 8X.xml'
